// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMd48YbMNdHKHiQBcMlMrn6DfskgtmMgI',
    appId: '1:438712862775:web:3e5233344d6f9d588517b2',
    messagingSenderId: '438712862775',
    projectId: 'todoapp-1e6b0',
    authDomain: 'todoapp-1e6b0.firebaseapp.com',
    storageBucket: 'todoapp-1e6b0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnwI4JzEJm9B90Z-PNRpjs4YsQWmDiAe8',
    appId: '1:438712862775:android:1af0b514e49b8dbd8517b2',
    messagingSenderId: '438712862775',
    projectId: 'todoapp-1e6b0',
    storageBucket: 'todoapp-1e6b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPs34TbxT4LldtSy3hIz0sofROoocU_Q4',
    appId: '1:438712862775:ios:f5799946fcb267768517b2',
    messagingSenderId: '438712862775',
    projectId: 'todoapp-1e6b0',
    storageBucket: 'todoapp-1e6b0.firebasestorage.app',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPs34TbxT4LldtSy3hIz0sofROoocU_Q4',
    appId: '1:438712862775:ios:f5799946fcb267768517b2',
    messagingSenderId: '438712862775',
    projectId: 'todoapp-1e6b0',
    storageBucket: 'todoapp-1e6b0.firebasestorage.app',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMd48YbMNdHKHiQBcMlMrn6DfskgtmMgI',
    appId: '1:438712862775:web:a92bcd4e400125bb8517b2',
    messagingSenderId: '438712862775',
    projectId: 'todoapp-1e6b0',
    authDomain: 'todoapp-1e6b0.firebaseapp.com',
    storageBucket: 'todoapp-1e6b0.firebasestorage.app',
  );
}
